package edu.wpi.aquamarine_axolotls.db;

import com.google.common.collect.BiMap;
import com.google.common.collect.EnumHashBiMap;

import static edu.wpi.aquamarine_axolotls.db.DatabaseInfo.*;

/**
 * Utility class for db package. Functionally static.
 */
public final class DatabaseUtil {

	private DatabaseUtil() {} //NO CONSTRUCTION ALLOWED >:(

	/**
	 * BiMap for associating SERVICEREQUEST enum with corresponding string representations.
	 */
	public final static BiMap<SERVICEREQUEST,String> SERVICEREQUEST_NAMES;

	/**
	 * BiMap for associating STATUS enum with corresponding string representations.
	 */
	public final static BiMap<STATUS,String> STATUS_NAMES;

	/**
	 * BiMap for associating ATTRIBUTE enum with corresponding string representations.
	 */
	public final static BiMap<ATTRIBUTE,String> ATTRIBUTE_NAMES;

	/**
	 * BiMap for associating USERTYPE enum with corresponding string representations.
	 */
	public final static BiMap<USERTYPE,String> USER_TYPE_NAMES;

	static {
		SERVICEREQUEST_NAMES = EnumHashBiMap.create(SERVICEREQUEST.class);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.EXTERNAL_TRANSPORT,EXTERNAL_TRANSPORT_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.FLORAL_DELIVERY,FLORAL_DELIVERY_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.FOOD_DELIVERY,FOOD_DELIVERY_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.GIFT_DELIVERY,GIFT_DELIVERY_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.INTERNAL_TRANSPORT,INTERNAL_TRANSPORT_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.LANGUAGE_INTERPRETER,LANGUAGE_INTERPRETER_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.LAUNDRY,LAUNDRY_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.MEDICINE_DELIVERY,MEDICINE_DELIVERY_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.RELIGIOUS_REQUEST,RELIGIOUS_REQUEST_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.SANITATION,SANITATION_TEXT);
		SERVICEREQUEST_NAMES.put(SERVICEREQUEST.SECURITY,SECURITY_TEXT);

		STATUS_NAMES = EnumHashBiMap.create(STATUS.class);
		STATUS_NAMES.put(STATUS.UNASSIGNED,UNASSIGNED_TEXT);
		STATUS_NAMES.put(STATUS.ASSIGNED,ASSIGNED_TEXT);
		STATUS_NAMES.put(STATUS.IN_PROGRESS,IN_PROGRESS_TEXT);
		STATUS_NAMES.put(STATUS.DONE,DONE_TEXT);
		STATUS_NAMES.put(STATUS.CANCELED,CANCELED_TEXT);

		ATTRIBUTE_NAMES = EnumHashBiMap.create(ATTRIBUTE.class);
		ATTRIBUTE_NAMES.put(ATTRIBUTE.NOT_NAVIGABLE,NOT_NAVIGABLE_TEXT);
		ATTRIBUTE_NAMES.put(ATTRIBUTE.HANDICAPPED_ACCESSIBLE,HANDICAPPED_ACCESSIBLE_TEXT);
		ATTRIBUTE_NAMES.put(ATTRIBUTE.COVID_SAFE,COVID_SAFE_TEXT);

		USER_TYPE_NAMES = EnumHashBiMap.create(USERTYPE.class);
		USER_TYPE_NAMES.put(USERTYPE.EMPLOYEE,EMPLOYEE_TEXT);
		USER_TYPE_NAMES.put(USERTYPE.PATIENT,PATIENT_TEXT);
		USER_TYPE_NAMES.put(USERTYPE.ADMIN,ADMIN_TEXT);
		USER_TYPE_NAMES.put(USERTYPE.GUEST,GUEST_TEXT);
	}
}
