package edu.wpi.cs3733.d21.teamA.db.enums;

/**
 * Enum for service request tables.
 */
public enum SERVICEREQUEST {
	EXTERNAL_TRANSPORT,
	FLORAL_DELIVERY,
	FOOD_DELIVERY,
	GIFT_DELIVERY,
	INTERNAL_TRANSPORT,
	LANGUAGE_INTERPRETER,
	LAUNDRY,
	MEDICINE_DELIVERY,
	SANITATION,
	FACILITIES_MAINTENANCE
}